# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GroupWidgetRadio.ui'
#
# Created: Tue Dec 25 11:14:14 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GroupWidget(object):
    def setupUi(self, GroupWidget):
        GroupWidget.setObjectName(_fromUtf8("GroupWidget"))
        GroupWidget.resize(604, 606)
        GroupWidget.setStyleSheet(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(GroupWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.group_label = QtGui.QLabel(GroupWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.group_label.setFont(font)
        self.group_label.setObjectName(_fromUtf8("group_label"))
        self.verticalLayout.addWidget(self.group_label)
        self.frame = QtGui.QFrame(GroupWidget)
        self.frame.setStyleSheet(_fromUtf8("#frame{\n"
"border: 1.5px solid rgb(190, 190, 190);\n"
"}"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.driver1 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.driver1.setFont(font)
        self.driver1.setObjectName(_fromUtf8("driver1"))
        self.horizontalLayout.addWidget(self.driver1)
        self.name1 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.name1.setFont(font)
        self.name1.setStyleSheet(_fromUtf8("QLabel{\n"
"    color: rgb(255, 0, 0)\n"
"}"))
        self.name1.setText(_fromUtf8(""))
        self.name1.setObjectName(_fromUtf8("name1"))
        self.horizontalLayout.addWidget(self.name1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radio11 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio11.setFont(font)
        self.radio11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio11.setChecked(True)
        self.radio11.setObjectName(_fromUtf8("radio11"))
        self.button_group_1 = QtGui.QButtonGroup(GroupWidget)
        self.button_group_1.setObjectName(_fromUtf8("button_group_1"))
        self.button_group_1.addButton(self.radio11)
        self.horizontalLayout_6.addWidget(self.radio11)
        self.radio12 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio12.setFont(font)
        self.radio12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio12.setObjectName(_fromUtf8("radio12"))
        self.button_group_1.addButton(self.radio12)
        self.horizontalLayout_6.addWidget(self.radio12)
        self.radio13 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio13.setFont(font)
        self.radio13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio13.setObjectName(_fromUtf8("radio13"))
        self.button_group_1.addButton(self.radio13)
        self.horizontalLayout_6.addWidget(self.radio13)
        self.radio14 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio14.setFont(font)
        self.radio14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio14.setObjectName(_fromUtf8("radio14"))
        self.button_group_1.addButton(self.radio14)
        self.horizontalLayout_6.addWidget(self.radio14)
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.driver2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.driver2.setFont(font)
        self.driver2.setObjectName(_fromUtf8("driver2"))
        self.horizontalLayout_2.addWidget(self.driver2)
        self.name2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.name2.setFont(font)
        self.name2.setStyleSheet(_fromUtf8("QLabel{\n"
"    color: rgb(255, 0, 0)\n"
"}"))
        self.name2.setText(_fromUtf8(""))
        self.name2.setObjectName(_fromUtf8("name2"))
        self.horizontalLayout_2.addWidget(self.name2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radio21 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio21.setFont(font)
        self.radio21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio21.setChecked(True)
        self.radio21.setObjectName(_fromUtf8("radio21"))
        self.button_group_2 = QtGui.QButtonGroup(GroupWidget)
        self.button_group_2.setObjectName(_fromUtf8("button_group_2"))
        self.button_group_2.addButton(self.radio21)
        self.horizontalLayout_8.addWidget(self.radio21)
        self.radio22 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio22.setFont(font)
        self.radio22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio22.setObjectName(_fromUtf8("radio22"))
        self.button_group_2.addButton(self.radio22)
        self.horizontalLayout_8.addWidget(self.radio22)
        self.radio23 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio23.setFont(font)
        self.radio23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio23.setObjectName(_fromUtf8("radio23"))
        self.button_group_2.addButton(self.radio23)
        self.horizontalLayout_8.addWidget(self.radio23)
        self.radio24 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio24.setFont(font)
        self.radio24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio24.setObjectName(_fromUtf8("radio24"))
        self.button_group_2.addButton(self.radio24)
        self.horizontalLayout_8.addWidget(self.radio24)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.driver3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.driver3.setFont(font)
        self.driver3.setObjectName(_fromUtf8("driver3"))
        self.horizontalLayout_3.addWidget(self.driver3)
        self.name3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.name3.setFont(font)
        self.name3.setStyleSheet(_fromUtf8("QLabel{\n"
"    color: rgb(255, 0, 0)\n"
"}"))
        self.name3.setText(_fromUtf8(""))
        self.name3.setObjectName(_fromUtf8("name3"))
        self.horizontalLayout_3.addWidget(self.name3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.radio31 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio31.setFont(font)
        self.radio31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio31.setChecked(True)
        self.radio31.setObjectName(_fromUtf8("radio31"))
        self.button_group_3 = QtGui.QButtonGroup(GroupWidget)
        self.button_group_3.setObjectName(_fromUtf8("button_group_3"))
        self.button_group_3.addButton(self.radio31)
        self.horizontalLayout_9.addWidget(self.radio31)
        self.radio32 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio32.setFont(font)
        self.radio32.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio32.setObjectName(_fromUtf8("radio32"))
        self.button_group_3.addButton(self.radio32)
        self.horizontalLayout_9.addWidget(self.radio32)
        self.radio33 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio33.setFont(font)
        self.radio33.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio33.setObjectName(_fromUtf8("radio33"))
        self.button_group_3.addButton(self.radio33)
        self.horizontalLayout_9.addWidget(self.radio33)
        self.radio34 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio34.setFont(font)
        self.radio34.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio34.setObjectName(_fromUtf8("radio34"))
        self.button_group_3.addButton(self.radio34)
        self.horizontalLayout_9.addWidget(self.radio34)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.driver4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.driver4.setFont(font)
        self.driver4.setObjectName(_fromUtf8("driver4"))
        self.horizontalLayout_4.addWidget(self.driver4)
        self.name4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.name4.setFont(font)
        self.name4.setStyleSheet(_fromUtf8("QLabel{\n"
"    color: rgb(255, 0, 0)\n"
"}"))
        self.name4.setText(_fromUtf8(""))
        self.name4.setObjectName(_fromUtf8("name4"))
        self.horizontalLayout_4.addWidget(self.name4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.radio41 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio41.setFont(font)
        self.radio41.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio41.setChecked(True)
        self.radio41.setObjectName(_fromUtf8("radio41"))
        self.button_group_4 = QtGui.QButtonGroup(GroupWidget)
        self.button_group_4.setObjectName(_fromUtf8("button_group_4"))
        self.button_group_4.addButton(self.radio41)
        self.horizontalLayout_10.addWidget(self.radio41)
        self.radio42 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio42.setFont(font)
        self.radio42.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio42.setObjectName(_fromUtf8("radio42"))
        self.button_group_4.addButton(self.radio42)
        self.horizontalLayout_10.addWidget(self.radio42)
        self.radio43 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio43.setFont(font)
        self.radio43.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio43.setObjectName(_fromUtf8("radio43"))
        self.button_group_4.addButton(self.radio43)
        self.horizontalLayout_10.addWidget(self.radio43)
        self.radio44 = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio44.setFont(font)
        self.radio44.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radio44.setObjectName(_fromUtf8("radio44"))
        self.button_group_4.addButton(self.radio44)
        self.horizontalLayout_10.addWidget(self.radio44)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(GroupWidget)
        QtCore.QMetaObject.connectSlotsByName(GroupWidget)

    def retranslateUi(self, GroupWidget):
        GroupWidget.setWindowTitle(QtGui.QApplication.translate("GroupWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.group_label.setText(QtGui.QApplication.translate("GroupWidget", "Gruppe:", None, QtGui.QApplication.UnicodeUTF8))
        self.driver1.setText(QtGui.QApplication.translate("GroupWidget", "Fahrer 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GroupWidget", "Platz:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio11.setText(QtGui.QApplication.translate("GroupWidget", "1.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio12.setText(QtGui.QApplication.translate("GroupWidget", "2.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio13.setText(QtGui.QApplication.translate("GroupWidget", "3.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio14.setText(QtGui.QApplication.translate("GroupWidget", "4.", None, QtGui.QApplication.UnicodeUTF8))
        self.driver2.setText(QtGui.QApplication.translate("GroupWidget", "Fahrer 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GroupWidget", "Platz:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio21.setText(QtGui.QApplication.translate("GroupWidget", "1.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio22.setText(QtGui.QApplication.translate("GroupWidget", "2.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio23.setText(QtGui.QApplication.translate("GroupWidget", "3.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio24.setText(QtGui.QApplication.translate("GroupWidget", "4.", None, QtGui.QApplication.UnicodeUTF8))
        self.driver3.setText(QtGui.QApplication.translate("GroupWidget", "Fahrer 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GroupWidget", "Platz:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio31.setText(QtGui.QApplication.translate("GroupWidget", "1.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio32.setText(QtGui.QApplication.translate("GroupWidget", "2.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio33.setText(QtGui.QApplication.translate("GroupWidget", "3.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio34.setText(QtGui.QApplication.translate("GroupWidget", "4.", None, QtGui.QApplication.UnicodeUTF8))
        self.driver4.setText(QtGui.QApplication.translate("GroupWidget", "Fahrer 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GroupWidget", "Platz:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio41.setText(QtGui.QApplication.translate("GroupWidget", "1.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio42.setText(QtGui.QApplication.translate("GroupWidget", "2.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio43.setText(QtGui.QApplication.translate("GroupWidget", "3.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio44.setText(QtGui.QApplication.translate("GroupWidget", "4.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("GroupWidget", "OK", None, QtGui.QApplication.UnicodeUTF8))

